### ISSUE TITLE
Bug: Handling multiple facets

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSBluesky#22]
There is a bug when handling multiple facets in a [post.](https://bsky.app/profile/jdhitsolutions.com/post/3lbazoazoub22)  I think the byte location shifts.

```json
{
  "record": {
    "$type": "app.bsky.feed.post",
    "text": "I have an open discussion topic if you want to add your thoughts on supporting 2FA in the PSBluesky #PowerShell module.",
    "createdAt": "2024-11-18T18:02:15.8878051-05:00",
    "facets": [
      {
        "index": {
          "byteStart": 162,
          "byteEnd": 173
        },
        "features": [
          {
            "$type": "app.bsky.richtext.facet#tag",
            "tag": "PowerShell"
          }
        ]
      },
      {
        "index": {
          "byteStart": 15,
          "byteEnd": 31
        },
        "features": [
          {
            "$type": "app.bsky.richtext.facet#link",
            "uri": "https://github.com/jdhitsolutions/PSBluesky/discussions/21"
          }
        ]
      }
    ]
  },
```

The original string was: `"I have an open [discussion topic](https://github.com/jdhitsolutions/PSBluesky/discussions/21) if you want to add your thoughts on supporting 2FA in the PSBluesky #PowerShell module."`

**Comment by ShaunLawrie** [comment]
The byte offsets for tags and mentions are being calculated first. After that the `record.text` is being modified [here](https://github.com/jdhitsolutions/PSBluesky/blob/main/functions/New-PSBlueSkyPost.ps1#L111C21-L111C33) which makes the offsets calculated for tags/mentions against the original `record.text` version, not the revised one.
You can quickly fix that by handling the markdown style links first because that's the only one mutating the original text.

The approach works until the message contains unicode characters that take more than one byte btw. It's unlikely to happen when someone is sending a message from the terminal but it can.

I only noticed because I was doing this in reverse. I was taking posts from my timeline and trying to use the facets to render them as links in the terminal and they were all off-by-one when emoji were present in the record.text.
https://github.com/jdhitsolutions/PSBluesky/pull/24/files#diff-1994ad15cb20c326911f9a70a3308644bc32ba2986d778de258a9c630bf3f46dR74

**Comment by jdhitsolutions** [comment]
I haven't had a chance to work on this so I appreciate your suggestion. That makes the most sense.

**Comment by jdhitsolutions** [comment]
I think I have this fixed in v2.1.0.

**Comment by jdhitsolutions** [comment]
This change has been released. Keeping this open until I'm sure this has been resolved.

**Comment by jdhitsolutions** [comment]
I think this has been resolved.,
